/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRecipeIndexRouteImport } from './routes/add-recipe/index'
import { Route as RecipeRecipesRouteImport } from './routes/recipe/recipes'
import { Route as RecipeMyRouteImport } from './routes/recipe/my'
import { Route as RecipeRecipeIdIndexRouteImport } from './routes/recipe/$recipeId/index'
import { Route as RecipeRecipeIdEditRouteImport } from './routes/recipe/$recipeId/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRecipeIndexRoute = AddRecipeIndexRouteImport.update({
  id: '/add-recipe/',
  path: '/add-recipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipesRoute = RecipeRecipesRouteImport.update({
  id: '/recipe/recipes',
  path: '/recipe/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeMyRoute = RecipeMyRouteImport.update({
  id: '/recipe/my',
  path: '/recipe/my',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdIndexRoute = RecipeRecipeIdIndexRouteImport.update({
  id: '/recipe/$recipeId/',
  path: '/recipe/$recipeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdEditRoute = RecipeRecipeIdEditRouteImport.update({
  id: '/recipe/$recipeId/edit',
  path: '/recipe/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipe/my': typeof RecipeMyRoute
  '/recipe/recipes': typeof RecipeRecipesRoute
  '/add-recipe/': typeof AddRecipeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipe/$recipeId/edit': typeof RecipeRecipeIdEditRoute
  '/recipe/$recipeId/': typeof RecipeRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipe/my': typeof RecipeMyRoute
  '/recipe/recipes': typeof RecipeRecipesRoute
  '/add-recipe': typeof AddRecipeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipe/$recipeId/edit': typeof RecipeRecipeIdEditRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipe/my': typeof RecipeMyRoute
  '/recipe/recipes': typeof RecipeRecipesRoute
  '/add-recipe/': typeof AddRecipeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipe/$recipeId/edit': typeof RecipeRecipeIdEditRoute
  '/recipe/$recipeId/': typeof RecipeRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/recipe/my'
    | '/recipe/recipes'
    | '/add-recipe/'
    | '/api/auth/$'
    | '/recipe/$recipeId/edit'
    | '/recipe/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/recipe/my'
    | '/recipe/recipes'
    | '/add-recipe'
    | '/api/auth/$'
    | '/recipe/$recipeId/edit'
    | '/recipe/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/recipe/my'
    | '/recipe/recipes'
    | '/add-recipe/'
    | '/api/auth/$'
    | '/recipe/$recipeId/edit'
    | '/recipe/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  RecipeMyRoute: typeof RecipeMyRoute
  RecipeRecipesRoute: typeof RecipeRecipesRoute
  AddRecipeIndexRoute: typeof AddRecipeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RecipeRecipeIdEditRoute: typeof RecipeRecipeIdEditRoute
  RecipeRecipeIdIndexRoute: typeof RecipeRecipeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-recipe/': {
      id: '/add-recipe/'
      path: '/add-recipe'
      fullPath: '/add-recipe/'
      preLoaderRoute: typeof AddRecipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/recipes': {
      id: '/recipe/recipes'
      path: '/recipe/recipes'
      fullPath: '/recipe/recipes'
      preLoaderRoute: typeof RecipeRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/my': {
      id: '/recipe/my'
      path: '/recipe/my'
      fullPath: '/recipe/my'
      preLoaderRoute: typeof RecipeMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId/': {
      id: '/recipe/$recipeId/'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId/'
      preLoaderRoute: typeof RecipeRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId/edit': {
      id: '/recipe/$recipeId/edit'
      path: '/recipe/$recipeId/edit'
      fullPath: '/recipe/$recipeId/edit'
      preLoaderRoute: typeof RecipeRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  RecipeMyRoute: RecipeMyRoute,
  RecipeRecipesRoute: RecipeRecipesRoute,
  AddRecipeIndexRoute: AddRecipeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RecipeRecipeIdEditRoute: RecipeRecipeIdEditRoute,
  RecipeRecipeIdIndexRoute: RecipeRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
